apiVersion: v2
appVersion: 0.0.0
description: application
name: application
type: application
version: 0.0.0
dependencies:
  - name: common
    version: 2.3.0
    repository: https://charts.alexbabel.com
    alias: application
  - name: mysql
    version: 8.8.11
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 15.5.1
    repository: https://charts.bitnami.com/bitnami
