apiVersion: v1
kind: Secret
metadata:
  name: application-environment-secret
  namespace: application
  labels:
    app.kubernetes.io/name: application-environment-secret
stringData:
  environment: |
    {{ .Values.application.files.environment | nindent 4 }}
type: Opaque
