apiVersion: v1
kind: Secret
metadata:
  name: mysql-ansible-job-secret
  namespace: application
  labels:
    app.kubernetes.io/name: mysql-ansible-job-secret
type: Opaque
stringData:
  inventory.yaml: |
    localhost:
      hosts:
        localhost:
      vars:
        ansible_python_interpreter: /usr/local/bin/python3

        server:
          host: {{ .Values.mysql.ansibleJob.host | quote }}
          port: {{ .Values.mysql.ansibleJob.port | default 3306 | quote }}
          user: {{ .Values.mysql.ansibleJob.user | default "root" | quote }}
          password: {{ .Values.mysql.ansibleJob.password | default .Values.mysql.auth.rootPassword | quote }}

        databases: {{ .Values.mysql.databases | toYaml | nindent 10 }}
