apiVersion: v1
kind: Secret
metadata:
  name: application-pull-secrets
  namespace: application
  labels:
    app.kubernetes.io/name: application-pull-secrets
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://ghcr.io": {
          "auth": "{{ index .Values.imagePullSecrets.github | b64enc }}"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
