imagePullSecrets:
  github: "[redacted]"
application:
  secret:
    GRAYLOG_ENDPOINT: https://[redacted]/gelf
  files:
    environment: |
      env=prod

      locale=de

      ; MySQL connection
      database=[redacted]

      ; ProxySQL sidecar
      database.cached.host=127.0.0.1
      database.cached.port=6033

      database.extend=[redacted]

      logger.level=ERROR

      makaira.mailer=[redacted]

      graylog=[redacted]

      makaira.elasticsearch=[redacted]

      makaira.picturesimilarityapi=[redacted]

      s3=[redacted]

      cloudinary=[redacted]

      makaira.cache.connection.host=redis://[redacted]

      maxmind.geoip2.geolite2.path=[redacted]

      auth0=[redacted]

      importer_scheduler_credentials=[redacted]

mysql:
  auth:
    rootPassword: "[redacted]"
    password: "[redacted]"
    replicationPassword: "[redacted]"

  databases:
    - name: "[redacted]"
      password: "[redacted]"
      database: "[redacted]"
    - name: "[redacted]"
      database: "[redacted]"
      password: "[redacted]"

proxysql:
  users:
    - name: "[redacted]"
      password: "[redacted]"
    - name: "[redacted]"
      password: "[redacted]"

redis:
  auth:
    password: "[redacted]"
