- name: Prepare system
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Make sure pymysql is present
      pip:
        name: pymysql
        state: present

    - name: Manage MySQL databases
      community.mysql.mysql_db:
        name: "{{ item.database }}"
        state: '{{ item.state | default("present") }}'

        login_host: "{{ server.host }}"
        login_port: "{{ server.port }}"
        login_user: "{{ server.user }}"
        login_password: "{{ server.password }}"
      with_items: "{{ databases }}"

    - name: Manage MySQL users
      community.mysql.mysql_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        host: "%"
        priv: "{{ item.database }}.*:ALL"
        state: '{{ item.state | default("present") }}'

        login_host: "{{ server.host }}"
        login_port: "{{ server.port }}"
        login_user: "{{ server.user }}"
        login_password: "{{ server.password }}"
      with_items: "{{ databases }}"
