apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: elasticsearch-s3-secrets
data:
  s3.client.default.access_key: {{ .Values.s3.accessId | b64enc | quote }}
  s3.client.default.secret_key: {{ .Values.s3.secretKey | b64enc | quote }}
